### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [cindyxue/CMPE131_2019Fall_Team1#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by nganluu17** [comment]
Hello. This is Ngan Luu

**Comment by cindyxue** [comment]
Hello! This is Xueer Xue.

**Comment by V0zz** [comment]
Hello. This is Veida Hernandez.

**Comment by NHWallace** [comment]
Hello, this is Nathaniel Wallace. This is group 1 in class section 05.

**Comment by aryankhadiri** [comment]
Hello This is Aryan Khadiri.

**Comment by ProfRojas** [comment]
Thanks!
